<a href="https://colab.research.google.com/github/AmanN07/My-ML-Journey/blob/main/tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#importing tensorflow

import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
#creating tensor with constant

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#checking the number of a tensor (ndim stands for number of dimensions)

scalar.ndim

0

In [ ]:
#creating a vector

vector = tf.constant([10, 10])
vector

1

In [ ]:
#checking the number of a tensor (ndim stands for number of dimensions)

vector.ndim

1

In [ ]:
#creating a matrix

matrix = tf.constant([[10, 7], 
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#creatign another matrix
#specifying the data type with dtpe parameter

another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [0., 9.]], dtype=tf.float16)
another_matrix 

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 0.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                       [[14, 15, 16],
                        [17, 18, 19]]], dtype= tf.float32)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 1.,  2.,  3.],
        [ 4.,  5.,  6.]],

       [[ 7.,  8.,  9.],
        [10., 11., 12.]],

       [[14., 15., 16.],
        [17., 18., 19.]]], dtype=float32)>

In [ ]:
tensor.ndim

3

what we have created so far:

* Scalar: a single number 
* Vector: a number with direction (e.g. : wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers(when n can be any number, a 0-dimensional tensor is scalar and one dimensional tensor is a vector 

**Creating Tensors with variables**

In [ ]:
tf.Variable 

tensorflow.python.ops.variables.Variable

In [ ]:
#creating the same tensor with tf.Variable() as above

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#let's change one of the tensor in our changeable tensor

changeable_tensor[0]
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#changing the unchangeable tensor ---> should give error

unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

Creating Random Tensors